# Generated by Django 4.0.1 on 2022-10-31 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conteudo_topico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.topico'),
        ),
    ]
