# Generated by Django 4.0.1 on 2022-10-31 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_conteudo_descricao_alter_topico_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='core.topico'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='ordem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
