# Generated by Django 4.0.1 on 2022-10-31 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_conteudo_topico_alter_topico_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='ordem',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='core.topico'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topico',
            name='ordem',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
