# Generated by Django 4.0.1 on 2022-10-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conteudo_ordem_alter_conteudo_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='ordem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topico',
            name='ordem',
            field=models.IntegerField(),
        ),
    ]
